name: CICD PIPELINE
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: building step
        run: echo "BUILD SUCCESSFULL"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: testing step
        run: echo "TEST SUCCESSFULL"
        
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy step
        run: echo "DEPLOY SUCCESSFULL"
