name: testing
on:
 pull_request:
   branches: 
     - dev
     - main
jobs:
 pullrequest:
  runs-on: ubuntu-latest
  steps:
   - name: testing repo
     run: |
      echo "Testing repo done1"
      echo "Testing repo done2"
