name: CICD PIPELINE
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: building step
        run: echo "BUILD SUCCESSFULL"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: testing step
        run: |
          echo "TEST SUCCESSFULL"
          echo ${{vars.name}}
        
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploy step
        run: echo "DEPLOY SUCCESSFULL"
